export enum RECORDING_TYPES {
  SET_CURRENT_RECORDING_METADATA = 'SET_CURRENT_RECORDING_METADATA',
  SET_DOWNLOAD_URL = 'SET_DOWNLOAD_URL',
  SET_BLOB_URL = 'SET_BLOB_URL',
  SET_IS_PLAYING = 'SET_IS_PLAYING',
  SET_CURRENT_TIME_SECONDS = 'SET_CURRENT_TIME_SECONDS',
  SET_IS_IN_FULLSCREEN = 'SET_IS_IN_FULLSCREEN',
  SET_IS_IN_PIP = 'SET_IS_IN_PIP',
}
