export enum RECORDING_TYPES {
  SET_CURRENT_RECORDING_METADATA = 'SET_CURRENT_RECORDING_METADATA',
  SET_DOWNLOAD_URL = 'SET_DOWNLOAD_URL',
  SET_BLOB_URL = 'SET_BLOB_URL',
  SET_IS_PLAYING = 'SET_IS_PLAYING',
  SET_IS_DRAGGING_TIME = 'SET_IS_DRAGGING_TIME',
  SET_IS_SKIPPING_TIME = 'SET_IS_SKIPPING_TIME',
  SET_CURRENT_TIME_MILLISECONDS = 'SET_CURRENT_TIME_MILLISECONDS',
  SET_IS_FULLSCREEN = 'SET_IS_FULLSCREEN',
  SET_IS_PIP = 'SET_IS_PIP',
  FASTFORWARD_TIME = 'FASTFORWARD_TIME',
  REWIND_TIME = 'REWIND_TIME',
}
