export enum VIDEO_STREAM_TYPES {
  SET_DOWNLOAD_URL = 'SET_DOWNLOAD_URL',
  SET_BLOB_URL = 'SET_BLOB_URL',
  // Set entire state
  SET_VIDEO_STREAM_STATE = 'SET_VIDEO_STREAM_STATE',
  RESET_VIDEO_STREAM_STATE = 'RESET_VIDEO_STREAM_STATE',
}
