export enum NAVIGATION_TYPES {
  SET_IS_DRAWER_OPEN = 'SET_IS_DRAWER_OPEN',
  SET_YOUR_UNITS_NAVIGATION_URL = 'SET_YOUR_UNITS_NAVIGATION_URL',
  SET_RECORDINGS_NAVIGATION_URL = 'SET_RECORDINGS_NAVIGATION_URL',
}
