export enum VIDEO_PLAYBACK_TYPES {
  SET_GLOBAL_IS_PLAYING = 'SET_GLOBAL_IS_PLAYING',
  SET_GLOBAL_CURRENT_TIME_MS = 'SET_GLOBAL_CURRENT_TIME_MS',
  SET_GLOBAL_CURRENT_VOLUME = 'SET_GLOBAL_CURRENT_VOLUME',
  SET_GLOBAL_IS_MUTED = 'SET_GLOBAL_IS_MUTED',
  // Set entire state
  SET_VIDEO_PLAYBACK_STATE = 'SET_VIDEO_PLAYBACK_STATE',
  RESET_VIDEO_PLAYBACK_STATE = 'RESET_VIDEO_PLAYBACK_STATE',
}
